### ISSUE TITLE
addWidget(...): argument 2 has unexpected type 'float'

### ISSUE THREAD

**Issue by Okxa** [PiOverFour/MPK-M2-editor#11]
So this does not work as is on my system. (Arch Linux, `python-pyqt5 5.15.6-7 (pyqt5)`, `python-pyqt5-sip 12.9.1-1`), because addWidget expects the 2nd parameter (row) to be `int`:

```
# ./mpk-m2-editor
Traceback (most recent call last):
  File "/home/asko/AUR/MPK-M2-editor/./mpk-m2-editor", line 374, in <module>
    ui.setupUi(MainWindow)
  File "/home/asko/AUR/MPK-M2-editor/ui/qt_ui.py", line 171, in setupUi
    prog["gridLayout_5"].addWidget(knob["knobGroupBox"], knob_i/4+1, knob_i%4, 1, 1)
TypeError: arguments did not match any overloaded call:
  addWidget(self, QWidget): too many arguments
  addWidget(self, QWidget, int, int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 2 has unexpected type 'float'
  addWidget(self, QWidget, int, int, int, int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 2 has unexpected type 'float'
```

The original code is, at line 171:

```python
prog["gridLayout_5"].addWidget(knob["knobGroupBox"], knob_i/4+1, knob_i%4, 1, 1)
```

`knob_i/4+1` results in floats, see below:

```python
>>> for knob_i in range(8): print(knob_i/4+1)
...
1.0
1.25
1.5
1.75
2.0
2.25
2.5
2.75
```

However something like this works, and places the knobs in right rows:

```python
# check if this knob goes on 1st row
prog["gridLayout_5"].addWidget(knob["knobGroupBox"], 1 if knob_i < 4 else 2, knob_i%4, 1, 1)
```

OR use the previous implementation, but cast the float to int, rounding the decimals away.

```python
prog["gridLayout_5"].addWidget(knob["knobGroupBox"],  int(knob_i/4+1), knob_i%4, 1, 1)
# results in 1 or 2. Atleast in this case.
>>> for knob_i in range(8): print(int(knob_i/4+1))
...
1
1
1
1
2
2
2
2
```

However AFAIK rowLayout index starts at 0, so maybe this is better?:

```python
prog["gridLayout_5"].addWidget(knob["knobGroupBox"],  int(knob_i/4), knob_i%4, 1, 1)
# results in 1 or 0
>>> for knob_i in range(8): print(int(knob_i/4))
...
0
0
0
0
1
1
1
1
```

**Comment by JerryLumpkins** [comment]
I implemented your last solution - casting to int and not incrementing, and it worked flawlessly.

Thanks

**Comment by PiOverFour** [comment]
Hello @Okxa and @JerryLumpkins,
thanks for the report! I couldn’t reproduce the issue on my system, but it makes sense anyway to use `int`s for this argument, and indeed indexing from 0.
I committed a slightly different fix, could you test it when you have time? I assume I had made a mistake in the first place since I did use an `int` for a similar thing at line 509.
Cheers, feel free to reopen if the issue is not fixed!

**Comment by PiOverFour** [comment]
(By the way, the `//` operator results in an `int` since it’s the floor division, or integer division, so no need to cast. Here is the output to that:)
``` python
>>> for knob_i in range(8): print(knob_i//4)
... 
0
0
0
0
1
1
1
1
```

**Comment by JerryLumpkins** [comment]
I pulled your latest code, and my Ubuntu Studio 22.04 is running it just fine.
:-)
Thank you for your work on this project.
