### ISSUE TITLE
Traduction manquante

### ISSUE THREAD

**Issue by trebmuh** [PiOverFour/MPK-M2-editor#7]
Dans une capture d'écran qu'@erwan35 a faite pour que je puisse la mettre dans la [page de documentation de mpk-m2-editor de LibraZiK-3](https://librazik.tuxfamily.org/doc3/logiciels/mpk-m2-editor), on peut voir que les mots "Bank" ("Bank A" et "Bank B" ne sont pas traduits.

**Comment by PiOverFour** [comment]
Ah oui en effet. J’ai ajouté cette traduction, dont je ne m’étais pas aperçu qu’elle manquait car les mots « BANK » n’apparaissaient en fait carrément pas chez moi.
Alors j’ai vu un autre problème d’interface qui faisait que tous les textes n’avaient pas la même taille, et qui venait des feuilles de style. Normalement c’est réparé aussi mais ce n’est testé que sur mon environnement de bureau (KDE Plasma), donc il se pourrait que l’apparence ait changé dans d’autres OS ou DE.
À tester…

![image](https://user-images.githubusercontent.com/6894749/98048154-7037d180-1e2d-11eb-86b7-86df15d44944.png)

**Comment by trebmuh** [comment]
Ça semble tout bon.
Je ferme en conséquence.
