### ISSUE TITLE
libjack-dev2 instead of libjack-dev

### ISSUE THREAD

**Issue by bartart3d** [PiOverFour/MPK-M2-editor#9]
Hi, 
I had an issue trying to get the dependencies right, I stumbled on libjack-dev, it's an empty package in latest ubuntustudio, 20.10. installing libjack2-dev seems to have solved the issue, it runs good as far as I can see.
Maybe you could add in you documentation that libjack-dev2 works too.
_edit: changed libjack-dev2 to libjack2-dev_

**Comment by PiOverFour** [comment]
Hello @bartart3d,
thanks for this information. I’m using Kubuntu 20.10 and the libjack-dev package works. I can’t install libjack-dev2 or find it on Ubuntu’s package list, the only one I find is [libjack-jackd2-dev](https://packages.ubuntu.com/en/focal/libjack-jackd2-dev). Is this the package you are referring to?  
I can’t find an Ubuntu Studio package list either, I assume it uses the same package distribution as the other flavours of Ubuntu?  
Before I update the documentation, can you tell me where I can find more info on this package?

**Comment by bartart3d** [comment]
Hello, 
my mistake, indeed, sorry, it's libjack-jackd2-dev. 
I have libjack-dev package in the list too, in synaptic. but when I try to install it now, synaptic warns me that it will uninstall a whole bunch of applications depending on libjack-jackd2-dev, basically replacing everything jackd2 with jackd1, which is not what is wanted either. 
Weird, that I don't get the 'empty package' warning now.
Here I found some material on the differences between jack1 and jack2 if that is what you want to know : [differences](https://github.com/jackaudio/jackaudio.github.com/wiki/Differences-between-jack1-and-jack2)
I'm not a developer, don't quite know my way through all the documentation.

grtz,
Bart

**Comment by PiOverFour** [comment]
Ooh I see!  
I don't have jack2 installed right now, so I didn't get any warning, but many users may. I'll edit the docs as soon as possible.
Thanks :)

**Comment by PiOverFour** [comment]
Thanks again for the report!
